language: node_js
sudo: required
before_script:
  - yarn global add polymer-cli
  - yarn install
node_js: stable
addons:
  chrome: stable
script:
  - xvfb-run polymer test --npm --skip-plugin local
dist: xenial
branches:
  only:
    - master
